name: Create and publish a Docker image

on:
  workflow_call:
    secrets:
      MY_GITHUB_PAT:
        required: true  # Enforce that the secret must be provided by the caller

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # This allows the GITHUB_TOKEN to interact with the container registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Verify GIT_PAT Secret
        run: |
          if [ -z "${{ secrets.MY_GITHUB_PAT }}" ]; then
            echo "GIT_PAT is not set."
            exit 1
          else
            echo "GIT_PAT is set."
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_PAT=${{ secrets.MY_GITHUB_PAT }}
