name: Build and Push Docker Images Dynamically (no yq)

on:
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract service names manually from docker-compose.yml
        id: extract_services
        run: |
          SERVICES=$(awk '/services:/ {flag=1; next} /^[^[:space:]]/ {flag=0} flag && /^[[:space:]]{2}[a-zA-Z0-9_-]+:/ {gsub(":",""); print $1}' docker-compose.yml)
          
          echo "SERVICES<<EOF" >> $GITHUB_ENV
          echo "$SERVICES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all services
        run: docker compose -f docker-compose.yml build

      - name: Tag and Push images dynamically
        run: |
          IMAGE_NAME_LC=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          
          for SERVICE in $SERVICES; do
            echo "Procesando servicio: $SERVICE"
            docker tag "${IMAGE_NAME_LC}_${SERVICE}" "${{ env.REGISTRY }}/${IMAGE_NAME_LC}-${SERVICE}:latest"
            docker push "${{ env.REGISTRY }}/${IMAGE_NAME_LC}-${SERVICE}:latest"
          done
