name: Create and publish a Docker image

on:
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images with Docker Compose
        run: docker compose -f docker-compose.yml build

      - name: Hardcode docker-compose image names
        run: |
          FRONTEND_IMAGE="chatbotauto-frontend"
          BACKEND_IMAGE="chatbotauto-backend"
          
          IMAGE_NAME_LC=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')

          echo "FRONTEND_IMAGE=$FRONTEND_IMAGE" >> $GITHUB_ENV
          echo "BACKEND_IMAGE=$BACKEND_IMAGE" >> $GITHUB_ENV
          echo "IMAGE_NAME_LC=$IMAGE_NAME_LC" >> $GITHUB_ENV

      - name: Tag and Push Docker Images
        run: |
          docker tag $FRONTEND_IMAGE ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}-frontend:latest
          docker tag $BACKEND_IMAGE ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}-backend:latest

          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}-frontend:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}-backend:latest
