name: Build and Push Docker Images Dynamically

on:
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Extract service names from docker-compose
        id: extract_services
        run: |
          SERVICES=$(yq '.services | keys | .[]' docker-compose.yml)
          echo "SERVICES<<EOF" >> $GITHUB_ENV
          echo "$SERVICES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all services
        run: docker compose -f docker-compose.yml build

      - name: Tag and Push images dynamically
        run: |
          IMAGE_NAME_LC=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          
          for SERVICE in $SERVICES; do
            TAG="${{ env.REGISTRY }}/${IMAGE_NAME_LC}-${SERVICE}:latest"
            echo "Tagging $SERVICE -> $TAG"
            docker tag "${IMAGE_NAME_LC}_${SERVICE}" "$TAG"
            docker push "$TAG"
          done
