name: Notify Teams

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      url:
        required: true
        type: string
      from_branch:
        required: true
        type: string
      to_branch:
        required: true
        type: string
      reviewers:
        required: true
        type: string
      pr_state:
        required: true
        type: string
      author:
        required: false
        type: string
      closer:
        required: false
        type: string
      source_repo:
        required: false
        type: string
    secrets:
      POWER_AUTOMATE_URL_CLOSED:
        required: true

jobs:
  call-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Teams
        env:
          WEBHOOK_URL: ${{ secrets.POWER_AUTOMATE_URL_CLOSED }}
        run: |

          reviewers='${{ inputs.reviewers }}'


          payload=$(jq -n \
            --arg title "${{ inputs.title }}" \
            --arg url "${{ inputs.url }}" \
            --arg from_branch "${{ inputs.from_branch }}" \
            --arg to_branch "${{ inputs.to_branch }}" \
            --arg pr_state "${{ inputs.pr_state }}" \
            --arg author "${{ inputs.author }}" \
            --arg closer "${{ inputs.closer }}" \
            --arg source_repo "${{ inputs.source_repo }}" \
            --argjson reviewers "$reviewers" \
            '{
              pr_title: $title,
              pr_url: $url,
              from_branch: $from_branch,
              to_branch: $to_branch,
              reviewers: $reviewers,
              pr_state: $pr_state,
              author: $author,
              closer: $closer,
              source_repo: $source_repo
            }'
          )

          echo "Payload to send: $payload"
          curl -X POST -H "Content-Type: application/json" -d "$payload" "$WEBHOOK_URL"

