name: Notify Teams on PR

on:
  workflow_call:
    inputs:
      pr_title:
        required: true
        type: string
      pr_url:
        required: true
        type: string
      from_branch:
        required: true
        type: string
      to_branch:
        required: true
        type: string
      reviewers:
        required: false
        type: string
    secrets:
      POWER_AUTOMATE_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Call Power Automate Webhook
        env:
          WEBHOOK_URL: ${{ secrets.POWER_AUTOMATE_URL }}
        run: |
          reviewers_json=$(echo '${{ inputs.reviewers }}' | jq -R -s -c 'split("\n")[:-1]')
          payload=$(jq -n \
            --arg title "${{ inputs.pr_title }}" \
            --arg url "${{ inputs.pr_url }}" \
            --arg from_branch "${{ inputs.from_branch }}" \
            --arg to_branch "${{ inputs.to_branch }}" \
            --argjson reviewers "$reviewers_json" \
            '{pr_title: $title, pr_url: $url, from_branch: $from_branch, to_branch: $to_branch, reviewers: $reviewers}')
          
          curl -X POST -H "Content-Type: application/json" -d "$payload" "$WEBHOOK_URL"
